# ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/ads_db
spring.datasource.username=postgres
spring.datasource.password=????_??????_??_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA + Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ??????????? (??? ??????? ?? ??????)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core=DEBUG

jwt.secret=super-secret-key-for-dev-must-be-long-enough
jwt.expiration.minutes=60
