spring.datasource.url=jdbc:postgresql://localhost:5432/ads_db
spring.datasource.username=app_user
spring.datasource.password=strong_password_here
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.liquibase=INFO
